language: python
dist: trusty
sudo: false
install: pip install coveralls
script: make test
python: '3.6'
after_success:
    - coveralls
    - make push-github-pages
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pip-faster
        - $HOME/.cache/venv-update
        - $HOME/.pre-commit
